version: '3'
services:
  influxdb:
    image: arm64v8/influxdb:2.7
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    build: ./telegraf
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
      - /dev:/dev
    devices:
      - /dev/i2c-1:/dev/i2c-1 # Make I2C available to read out data
    env_file:
      - .env
    depends_on:
      - influxdb

volumes:
  influxdb-storage:
