version: '3.6'
services:
  telegraf:
    image: telegraf-custom
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /dev:/dev
    devices:
    - "/dev/i2c-1/:dev/i2c-1" # Make I2C available to read out data
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

  influxdb:
    image: arm64v8/influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=jo_admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=jo_org
      - DOCKER_INFLUXDB_INIT_BUCKET=co2
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data: {}



