version: '3'
services:
  influxdb:
    image: arm64v8/influxdb:2.6
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  scd30:
    build: .
    volumes:
      - ./scd30.py:/app/scd30.py
      - /dev:/dev
    devices:
      - /dev/i2c-1:/dev/i2c-1 # Make I2C available to read out data
    depends_on:
      - influxdb

volumes:
  influxdb-storage
