version: '3.6'
services:
  influxdb:
    image: arm64v8/influxdb:2.7
    volumes:
      - influxdb_data:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    container_name: influxdb
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    # environment:
    #   - DOCKER_INFLUXDB_INIT_MODE=setup
    #   - DOCKER_INFLUXDB_INIT_USERNAME=myadmin
    #   - DOCKER_INFLUXDB_INIT_PASSWORD=mypassword
    #   - DOCKER_INFLUXDB_INIT_ORG=myorg
    #   - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
    #   - DOCKER_INFLUXDB_INIT_RETENTION=30d

  telegraf:
    image: telegraf-custom
    container_name: telegraf
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

volumes:
  influxdb_data: {}
