version: '3'
services:
  influxdb:
    image: arm64v8/influxdb:2.7
    env_file:
      - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    restart: on-failure:10
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUX_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}

  telegraf:
    image: telegraf-custom
    container_name: telegraf
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
      - /dev:/dev
    devices:
      - /dev/i2c-1:/dev/i2c-1 # Make I2C available to read out data
    env_file:
      - influxv2.env
    depends_on:
      - influxdb

volumes:
  influxdbv2:
